- name: Install docker 
  yum: name=docker state=present
  tags: docker

- name: Configure docker
  template: src=docker_sysconfig.j2 dest=/etc/sysconfig/docker
  tags: docker
#  notify: restart docker

- name: Start docker
  service: name=docker state=started enabled=yes
  tags: docker

- name: Install docker-registry 
  yum: name=docker-registry state=present
  tags: docker-registry

- name: Configure docker-registry
  template: src=docker-storage-setup_sysconfig.j2 dest=/etc/sysconfig/docker-storage-setup
  tags: docker-registry

- name: Create docker storage
  shell: "docker-storage-setup"
  tags: docker-registry

- name: Start docker-registry
  service: name=docker-registry state=started enabled=yes
  tags: docker-registry